appname: helmut4

nodePorts:
  traefik:
    port: 30000
    addresses: 0.0.0.0 #comma separated list of ip's to listen to

containerResources:
  resources:
    requests:
      memory: "200Mi"
      cpu: "250m"
    limits:
      memory: "500Mi"
      cpu: "500m"

appVolumeMounts:

images:
  mcp_fx:
    name: repo.moovit24.de:443/mcp_fx
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcp_io:
    name: repo.moovit24.de:443/mcp_io
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcp_co:
    name: repo.moovit24.de:443/mcp_co
    version: 4.1.1.0
    imagePullPolicy: IfNotPresent
  mcp_hk:
    name: repo.moovit24.de:443/mcp_hk
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcp_hw:
    name: repo.moovit24.de:443/mcp_hw
    version: 4.1.1.2
    imagePullPolicy: IfNotPresent
  mcp_hp:
    name: repo.moovit24.de:443/mcp_hp
    version: 4.1.1.0
    imagePullPolicy: IfNotPresent
  mcc_amqp:
    name: repo.moovit24.de:443/mcc_amqp
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_cronjob:
    name: repo.moovit24.de:443/mcc_cronjob
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_language:
    name: repo.moovit24.de:443/mcc_language
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_license:
    name: repo.moovit24.de:443/mcc_license
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_logging:
    name: repo.moovit24.de:443/mcc_logging
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_metadata:
    name: repo.moovit24.de:443/mcc_metadata
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_preferences:
    name: repo.moovit24.de:443/mcc_preferences
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_streams:
    name: repo.moovit24.de:443/mcc_streams
    version: 4.1.1.0
    imagePullPolicy: IfNotPresent
  mcc_users:
    name: repo.moovit24.de:443/mcc_users
    version: 4.1.0.1
    imagePullPolicy: IfNotPresent
  mcc_rabbitmq:
    name: repo.moovit24.de:443/sev_rabbitmq
    version: 1.0.0.1
    imagePullPolicy: IfNotPresent
  mcc_traefik:
    name: repo.moovit24.de:443/mcc_traefik
    version: 4.0.5.3 # with open prometheus port 8082
    imagePullPolicy: IfNotPresent
  mcc_mongodb:
    name: repo.moovit24.de:443/mcc_mongodb
    version: 4.0.7.9
    imagePullPolicy: IfNotPresent
  mcc_mongodb_admin:
    name: repo.moovit24.de:443/mcc_mongodb_admin
    version: 4.0.1.1
    imagePullPolicy: IfNotPresent
  mcc_mongodb_backup:
    name: repo.moovit24.de:443/mcc_mongodb_backup
    version: 4.1.0.4
    imagePullPolicy: IfNotPresent
  prometheus:
    name: prom/prometheus
    version: v2.33.4
    imagePullPolicy: IfNotPresent

registryCredentials:
  registry: repo.moovit24.de:443
  username: moovit
  password: public

extraAppVolumeDatabase:
  hostPath:

extraAppVolumeDatabaseBackups:
  hostPath:

mongodbSettings:
  port: 27107
  username: root
  password: bitte
  backup:
    CRON_TIME: 0 */4 * * *
    MAX_BACKUPS: 180
    INIT_BACKUP: true